### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by Akuli** [fboender/hircd#1]
Would a pull request upgrading hircd to Python 3 be accepted? I use hircd for developing an irc client, and I don't want to require everyone to install Python 2 just to develop my irc client.

**Comment by fboender** [comment]
Thanks for the PR. I merged it just now. FYI, the default [Python IRC client library](https://github.com/jaraco/irc) also contains [a server](https://github.com/jaraco/irc/blob/main/irc/server.py). It's based on HIRCD, but it's better maintained. Not sure if you're developing your client on top of this library, but if so, you could also use the embedded server from that.
